/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_abhan_example_AbhanNativeFilter */

#ifndef _Included_com_abhan_example_AbhanNativeFilter
#define _Included_com_abhan_example_AbhanNativeFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_abhan_example_AbhanNativeFilter
 * Method:    sketchFilter
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_abhan_example_AbhanNativeFilter_sketchFilter
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
